onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - simple-git-hooks

patchedDependencies:
  '@echogarden/icu-segmentation-wasm': patches/@echogarden__icu-segmentation-wasm.patch
